# Use postgres/example user/password credentials
version: '3.9'

volumes:
    postgres:

services:
  postgres:
    image: postgres:13.3
    environment:
      POSTGRES_DB: "postgres.db"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "example"
    volumes:
      - ../2. Init Database:/docker-entrypoint-initdb.d
      - .:/var/lib/postgresql/data
    ports:
      - "8080:8080"
    restart: unless-stopped














